# Generated by Django 5.2.6 on 2025-09-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
