# Generated by Django 5.2.6 on 2025-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_remove_donorprofile_user_donorprofile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(default='', max_length=100)),
                ('required_quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(default='')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
