# Generated by Django 5.2.6 on 2025-09-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0003_patientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='city',
            new_name='address',
        ),
    ]
