# Generated by Django 5.2.6 on 2025-09-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0005_donorprofile_user_patientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='name',
        ),
    ]
