# Generated by Django 5.2.6 on 2025-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0006_remove_donorprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
