# Generated by Django 5.2.6 on 2025-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0007_donorprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5, unique=True)),
                ('units', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
